config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get '/terms', to: "pages#terms"
  get '/legislation', to: "pages#legislation"
  get '/discover', to: "pages#discover"
  get '/about', to: "pages#about"


  devise_for :users

  resources :jobs, only: [:index, :show] do
    resources :bids, only: [:new, :create]
  end

  resources :pilots, only: [:index, :show]

  namespace :inquirer do
    resources :jobs do
      resources :bids, only: [:update] do
        member do
          patch :accept
        end
      end
    end
  end

  namespace :owner do
    resource :profile, only: [:show, :edit, :update]

    resources :drones
  end

  resources :jobs do
    collection do
      get 'latest', to: "jobs#latest"
    end
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user

  has_many :bids, dependent: :destroy
  has_many :drones, through: :bids

  has_many :job_categories, dependent: :destroy
  has_many :categories, through: :job_categories

  def self.search(search)
    where("location ILIKE ? ", "%#{search}%")
  end

  scope :latest, -> { order('created_at')[0..2] }
end

app/controllers/inquirer/bids_controller.rb
module Inquirer
  class BidsController < ApplicationController
    def accept
      @bid = Bid.find(params[:id])
      @job = Job.find(params[:job_id])
      @bid.status = "accepted"
      @bid.save!
      redirect_to job_path(@job)
    end

    private

    def bid_params
      params.require(:bid).permit(:status, :id, :job_id)
    end
  end
end

app/controllers/inquirer/jobs_controller.rb
module Inquirer
  class JobsController < ApplicationController
    def index
      @jobs = current_user.jobs
    end

    def show
      @job = Job.find(params[:id])
    end

    def new
      @job = Job.new
    end

    def create
      @job = Job.new(job_params)
      @job.user = current_user
      @job.save!
      redirect_to inquirer_jobs_path(@job)
    end

    def edit
      @job = Job.find(params[:id])
    end

    def update
      @job = Job.find(params[:id])
      @job.update(job_params)
      redirect_to inquirer_jobs_path(@job)
    end

    def destroy
      @job = Job.find(params[:id])
      @job.destroy
      redirect_to inquirer_jobs_path
    end

    private

    def job_params
      params.require(:job).permit(:description, :location, :date, :user_id, :title)
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_drones
  skip_before_action :authenticate_user!

  def index
    if params[:what] != "pilot"
      if params[:search]
        # Search is location based
        @jobs = Job.search(params[:search]).order("created_at DESC")
      elsif params[:category]
        # Search is category based
        @selected_category = Category.find_by(name: params[:category])
        @jobs = Job.joins(:categories).where(categories: { id: @selected_category.id })
      else
        @jobs = Job.all.order("created_at DESC")
      end
    else
      redirect_to pilots_path(search: params[:search])
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def latest
    # get a list of 3 jobs that have been posted latest
    @jobs = Job.latest
  end

  private

  def set_drones
    if !current_user.nil?
      @drones = current_user.drones
    end
  end
end

app/views/inquirer/jobs/_form.html.erb
<%= simple_form_for([ :inquirer, @job]) do |f| %>
  <%= f.error_notification %>

<!-- f.input name -->
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :date %>

  <%= f.button :submit %>
<% end %>

app/views/inquirer/jobs/_modal_new.html.erb
<!-- Modal -->
<div class="modal fade" id="modal-job" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= simple_form_for([:inquirer, Job.new]) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create a job</h4>
      </div>
      <div class="modal-body">
        <%= f.error_notification %>

        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :date %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/inquirer/jobs/edit.html.erb
<h1 class="text-center">Edit this Job</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <%= simple_form_for([ :inquirer, @job]) do |f| %>
      <%= f.error_notification %>

      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :location %>
      <%= f.input :date %>

      <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/inquirer/jobs/index.html.erb
<div class="banner dashboard" style="background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.6)), url(<%= current_user.banner_pic %>);">
  <div class="banner-content">
    <% if current_user.profile_pic.nil? %>
      <%= image_tag "http://placehold.it/300x300", alt: "profile picture" %>
    <% else %>
      <%= cl_image_tag current_user.profile_pic.url, height: 300, width: 300, crop: :fill %>
    <% end %>
    <h1><%= current_user.first_name %> <%= current_user.last_name %></h1>
    <div class="banner-content-description"><%= current_user.description %></div>
    <div class="banner-content-buttons">
      <%= link_to "Edit your Profile", '#', { class: "btn btn-primary edit-profile", data: { toggle: "modal", target: "#modal-profile"}} %>
      <%= link_to "See All Jobs", jobs_path, class: "btn btn-primary see-profile" %>
    </div>
  </div>
</div>

<% @owner = current_user %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <div class="row">
        <div class="col-xs-12">
          <h2>Your listed jobs</h2>
        </div>
      </div>
      <hr>
      <% @jobs.each do |job| %>
      <div class="row">
        <div class="job-details">
          <div class="job-user">
            <div class="col-xs-12">
              <div class="job-user-block">
                <div class="user-block-avatar">
                  <%= cl_image_tag job.user.profile_pic.url, size: "32x32", crop: :fill, style: "border-radius: 50%;" %>
                </div>
                <div class="user-block-description">
                  <a href=""><%=job.user.first_name%> <%=job.user.last_name%></a>
                  <p><%= l(job.created_at, format: :date) %></p>
                </div>
              </div>
              <div class="job-description-block">
                <h2><%= link_to job.title, job_path(job) %></h2>

                <p class="job-description"><%=job.description%></p>
                <h6><%= link_to "Read more...", job_path(job) %></h6>
              </div>
              <div class="job-footer">
                <div class="job-footer-spec">
                  <p>
                    <span>
                      TAGS: <%= category_human_names(job) %>
                    </span>
                    <span>
                      <i class="fa fa-map-marker"></i> <%=job.location%> |
                    </span>
                    <span>
                      <i class="fa fa-calendar"></i> <%=job.date%>  |
                    </span>
                  </p>
                </div>
                <div class="job-footer-bid">
                  <p>
                    <span>
                      <i class="fa fa-gavel"></i> <%= job.bids.count %> bids  |
                    </span>
                    <span>
                      <%= link_to "Edit job", edit_inquirer_job_path(job), { class: "btn btn-default" } %>
                      <%= link_to "Delete job", inquirer_job_path(job),  class: "btn btn-default" ,
                      method: :delete,
                      data: { confirm: "Are you sure?" }%>
                    </span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= link_to "Create a new job", '#', { class: "btn btn-primary btn-xs cta-discover", data: {'job-id': @job, toggle: "modal", target: "#modal-job"}} %>
    </div>
  </div>
</div>
<%= render 'inquirer/jobs/modal_new' %>
<%= render 'owner/profiles/modal_edit' %>

app/views/inquirer/jobs/new.html.erb
<h1 class="text-center"> Create a new job </h1>

<div class="container"> 
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/inquirer/jobs/show.html.erb
<div class="container">

<h2>Job.title</h2>

<h4>Description</h4>
<p><%= @job.description %></p>

<h4>Location</h4>
<p><%= @job.location %></p>

<h4>Bids</h4>
<% if @job.bids == [] %>
<p>There are no bids on this job at the moment</p>
<% else %>
<table class="table">
<tr>
  <th>Amount</th>
  <th>Bidder</th>
  <th>Description</th>
  <% if @job.user == current_user %>
  <th></th>
  <% end %>
</tr>
<% @job.bids.each do |bid| %>
  <tr>
    <td>€<%= bid.amount %></td>
    <td><%= bid.drone.user.first_name %></td>
    <td><%= bid.description %></td>
    <% if @job.user == current_user %>
    <td>
      <%= simple_form_for([:inquirer, @job, bid]) do |f| %>
        <%= f.error_notification %>
        <%= f.input_field :status, collection: ["open", "accepted", "closed"], prompt: "open" %>
        <%= f.button :submit %>
      <% end %>
      <!--  link_to "Accept Bid", accept_inquirer_job_bid_path(@job, bid)-->
      </td>
    <% end %>
  </tr>
<% end %>
</table>
<% end %>
</div>