config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get '/terms', to: "pages#terms"
  get '/legislation', to: "pages#legislation"
  get '/discover', to: "pages#discover"
  get '/about', to: "pages#about"


  devise_for :users

  resources :jobs, only: [:index, :show] do
    resources :bids, only: [:new, :create]
  end

  resources :pilots, only: [:index, :show]

  namespace :inquirer do
    resources :jobs do
      resources :bids, only: [:update] do
        member do
          patch :accept
        end
      end
    end
  end

  namespace :owner do
    resource :profile, only: [:show, :edit, :update]

    resources :drones
  end

  resources :jobs do
    collection do
      get 'latest', to: "jobs#latest"
    end
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user

  has_many :bids, dependent: :destroy
  has_many :drones, through: :bids

  has_many :job_categories, dependent: :destroy
  has_many :categories, through: :job_categories

  def self.search(search)
    where("location ILIKE ? ", "%#{search}%")
  end

  scope :latest, -> { order('created_at')[0..2] }
end

app/controllers/inquirer/jobs_controller.rb
module Inquirer
  class JobsController < ApplicationController
    def index
      @jobs = current_user.jobs
    end

    def show
      @job = Job.find(params[:id])
    end

    def new
      @job = Job.new
    end

    def create
      @job = Job.new(job_params)
      @job.user = current_user
      @job.save!
      redirect_to inquirer_jobs_path(@job)
    end

    def edit
      @job = Job.find(params[:id])
    end

    def update
      @job = Job.find(params[:id])
      @job.update(job_params)
      redirect_to inquirer_jobs_path(@job)
    end

    def destroy
      @job = Job.find(params[:id])
      @job.destroy
      redirect_to inquirer_jobs_path
    end

    private

    def job_params
      params.require(:job).permit(:description, :location, :date, :user_id, :title)
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_drones
  skip_before_action :authenticate_user!

  def index
    if params[:what] != "pilot"
      if params[:search]
        # Search is location based
        @jobs = Job.search(params[:search]).order("created_at DESC")
      elsif params[:category]
        # Search is category based
        @selected_category = Category.find_by(name: params[:category])
        @jobs = Job.joins(:categories).where(categories: { id: @selected_category.id })
      else
        @jobs = Job.all.order("created_at DESC")
      end
    else
      redirect_to pilots_path(search: params[:search])
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def latest
    # get a list of 3 jobs that have been posted latest
    @jobs = Job.latest
  end

  private

  def set_drones
    if !current_user.nil?
      @drones = current_user.drones
    end
  end
end

app/views/jobs/_index.html.erb
<div class="jobs-body">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h2 class="subtitle"><span>Jobs</span></h2>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 col-sm-offset-1">
      <div class="sidebar hidden-xs">
        <ul>
          <h5>CATEGORIES</h5>
          <hr>
          <!-- this list should be called with an each statement over each of the categories. Capitals can be changed in css with capitalize -->
          <li><a href="#all" class="active">ALL CATEGORIES</a></li>
          <li><a href="#fun">EDUCATION</a></li>
          <li><a href="#agriculture">ENVIRONMENT</a></li>
          <li><a href="#fun">FAMILY</a></li>
          <li><a href="#festival">FESTIVAL</a></li>
          <li><a href="#fun">FUN</a></li>
          <li><a href="#other">OTHER</a></li>
          <li><a href="#sport">SPORT</a></li>
          <li><a href="#wedding">WEDDING</a></li>
        </ul>
      </div>
    </div>
    <!-- this content should change together with the changing href or the class active -->
    <div class="col-md-8">
      <h5>JOBS > <a href="#all" class="active">ALL CATEGORIES</a></h5>
      <div class="banner-jobs">
        <div class="banner-content">
          <h1>All categories</h1>
          <p>Find your pilot</p>
        </div>
      </div>

      <% @jobs.each do |job|%>
      <div class="row">
        <div class="col-xs-12">
          <div class="job-details">
            <div class="job-user">
              <%= image_tag "jobs/iris.png", class:"list-avatar"%>
              <h6><i class="fa fa-gavel"></i> 2 bids</h6>
              <!-- this h6-content will change to 'place first bid' || the amount of bids placed -->
              <%= link_to "Place a bid", '#', { class: "btn btn-primary new-bid btn-sm", data: {'job-id': job.id, toggle: "modal", target: "#modal-bid"}} %> 
            </div>
            <div>            
              <h4><%=job.user.first_name%></h4>
              <h6>WEDDING</h6>
              <!-- this h6-content tag will change with the category -->
              <p><%=job.description%></p>
            </div> 
          </div>
        </div>
      </div>
      <!-- show 10max and allow user to show the next 10 etc.  -->
      <% end %>

    </div>
  </div>
</div>

<%= render 'bids/modal_new' %>

app/views/jobs/index.html.erb
<!-- <div class="banner jobs" id="all_categories"></div> -->
<%= render 'pages/discover_tabs', active_tab: 'jobs' %>
<div class="jobs-body">
  <div class="container">

    <div class="col-xs-2">
      <div class="sidebar hidden-xs">
        <ul>
          <h5>CATEGORIES</h5>
          <li><%= link_to "ALL CATEGORIES", jobs_path %></li>
          <% Category.all.each do |c| %>
          <li class="<%=  @selected_category == c ? "cat_active" : "cat" %>"><%= link_to c.name.upcase, jobs_path(category: c.name) %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="col-xs-12 col-md-10">
      <h5>JOBS >
       <% if @selected_category %>
       <span><%= @selected_category.name.upcase %></span>
       <% else %>
       <span>ALL CATEGORIES</span>
       <% end %>
       <%= link_to "How to create a job", about_path, { class: "btn btn-primary cta-discover"} %>
     </h5>

     <% if @selected_category %>
     <div class="banner jobs" style="background-image: url('<%= image_path(@selected_category.name + ".jpg") %>')">
      <% else %>
      <div class="banner jobs">
        <% end %>

        <div class="banner-content" id="all_categories">
          <% if @selected_category %>
          <h1><%= @selected_category.name.capitalize %></h1>
          <% else %>
          <h1>All categories</h1>
          <% end %>
          <p>Find your pilot</p>
        </div>
      </div>
      <% if !@jobs.empty? %>
      <% @jobs.each do |job|%>
      <div class="row">
        <div class="job-details">
          <div class="job-user">
            <div class="col-xs-12">
              <div class="job-user-block">
                <div class="job-user-block-profile">
                  <div class="user-block-avatar">
                    <%= cl_image_tag job.user.profile_pic.url, size: "35x35", crop: :fill, style: "border-radius: 50%; object-fit: cover;" %>
                  </div>
                  <div class="user-block-description">
                    <a href=""><%=job.user.first_name%> <%=job.user.last_name%></a>
                    <p><%=job.created_at.strftime('%A, %b %d') %></p>
                  </div>
                </div>
              </div>
              <div class="job-description-block">
                <h2><%= link_to job.title, job_path(job) %></h2>

                <p><%=job.description%></p>
                <span><%= link_to "Read more...", job_path(job) %></span>
              </div>
              <div class="job-footer">
                <div class="job-footer-spec">
                <p>
                      TAGS: <%= category_human_names(job) %> 
                      <span>*</span>
                      <i class="fa fa-map-marker"></i> <%=job.location%> 
                      <span>*</span>
                      <i class="fa fa-calendar"></i> <%=job.date%>
                </p>
                </div>
                <div class="job-footer-bid">  <p>
                  <span>
                    <i class="fa fa-gavel"></i> <%= job.bids.count %> bids  |
                  </span>
                  <% if !current_user.nil? && current_user.owner == true %>
                  <span>
                    <%= link_to "Place a bid", '#', { class: "btn btn-primary new-bid btn-xs", data: {'job-id': job.id, toggle: "modal", target: "#modal-bid"}} %>
                  </span>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- show 10max and allow user to show the next 10 etc.  -->
    <% end %>
    <% else %>
    <p>No jobs yet</p>
    <% end %>

  </div>
</div>
</div>
</div>

<%= render 'bids/modal_new', job: Job.first, drones: @drones %>

app/views/jobs/show.html.erb
<div class="transparent-top"></div>
<div id="map" style="width: 100%;height: 400px;"></div>
<script>
  function initMap() {
    var styles = [{"featureType":"road","elementType":"geometry","stylers":[{"lightness":100},{"visibility":"simplified"}]},{"featureType":"water","elementType":"geometry","stylers":[{"visibility":"on"},{"color":"#C6E2FF"}]},{"featureType":"poi","elementType":"geometry.fill","stylers":[{"color":"#C5E3BF"}]},{"featureType":"road","elementType":"geometry.fill","stylers":[{"color":"#D1D1B8"}]},{
      featureType: "road",
      elementType: "labels",
      stylers: [
      { visibility: "off" }
      ]
    }];
    var myLatLng = {lat: 52.34304, lng: 4.82928};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 11,
      center: myLatLng,
      scrollwheel:  false,
      styles: styles
    });
    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      title: 'B.Amsterdam!'
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
async defer></script>

<div class="container padding-top">
  <div class="row">
    <div class="job-details">
      <div class="job-user">
        <div class="col-xs-12 col-md-2 col-md-offset-1">
          <div class="text-center">
            <%= cl_image_tag @job.user.profile_pic.url, size: "125x125", crop: :fill, style: "border-radius: 50%; padding: 5px;" %>
            <h5><%=@job.user.first_name%> <%=@job.user.last_name%></h5>
          </div>
        </div>
        <div class="col-xs-12 col-md-8">
          <h3><%= @job.title %></h3>
          <p class="job-description"><%=@job.description%></p>
          <div class="job-footer-spec">
            <p>
              TAGS: <%= category_human_names(@job) %> 
              <span>*</span>
              <i class="fa fa-map-marker"></i> <%=@job.location%>
              <span>*</span>
              <i class="fa fa-calendar"></i> <%=@job.date%> 
              <span></span>
              <% if !current_user.nil? %>
              <% if current_user.owner == true %>
              <%= link_to "Place a bid", '#', { class: "btn btn-primary new-bid btn-xs", data: {'job-id': @job.id, toggle: "modal", target: "#modal-bid"}} %>
              <% end %>
              <% end %>
            </p>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>

<div class="container bid-details">
  <h2 class="subtitle"><span><i class="fa fa-gavel"></i>Bids<i class="fa fa-gavel fa-rotate-90"></i></span></h2>

  <% if @job.bids.empty? %>
  <% if !current_user.nil? %>
  <% if current_user.owner == true %>
  <p class="text-center">No bids yet. Be the first to place a bid!</p>
  <% elsif @job.user == current_user %>
  <p class="text-center">There are no bids on your job yet.</p>
  <% else %>
  <p class="text-center">There are no bids on this job.</p>
  <% end %>
  <% end %>
  <% else %>

  <% @job.bids.each do |bid|%>
  <div class="bid-list">
    <div class="row">
      <div class="job-user-block">
        <div class="job-user-block-profile">
          <div class="user-block-avatar">
            <%= cl_image_tag bid.drone.user.profile_pic.url, size: "35x35", alt: "profile picture", crop: :fill, style: "border-radius: 50%; object-fit: cover;" %>
          </div>
          <div class="user-block-description">
            <a href=""><%=bid.drone.user.first_name%> <%=bid.drone.user.last_name%></a>
            <p><%=bid.created_at.strftime('%A, %b %d') %></p>
          </div>
        </div>
        <div class="bid-amount">
          <h3 class="text-right">€ <%= bid.amount %></h3>
          <% if @job.user == current_user %>
          <div class="user-accept-bid">
            <%= link_to "Accept Bid", accept_inquirer_job_bid_path(@job, bid), method: :patch, class: "btn btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="bid-description-block">
        <div class="bids-description">
          <p><%= bid.description %></p>
        </div>
        <div class="bids-drone-description">
          <div class="job-user-block-drone">
            <div class="bid-drone-block-avatar">
              <%= cl_image_tag bid.drone.photo.url, size: "95x95", alt: "drone", style: "border-radius: 50%; padding: 5px; object-fit: cover;"%>
            </div>
            <div class="bid-drone-label">
              <ul>
                <li>BRAND</li>
                <li>MODEL</li>
                <li>CAMERA</li>
              </ul>
            </div>
            <div class="bid-drone-value">  
              <ul>
                <li><%=bid.drone.brand%></li>
                <li><%=bid.drone.model%></li>
                <li><%=bid.drone.camera%></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% end %>
  <% end %>

</div>
<%= render 'bids/modal_new', job: @job, drones: @drones %>