config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get '/terms', to: "pages#terms"
  get '/legislation', to: "pages#legislation"
  get '/discover', to: "pages#discover"
  get '/about', to: "pages#about"


  devise_for :users

  resources :jobs, only: [:index, :show] do
    resources :bids, only: [:new, :create]
  end

  resources :pilots, only: [:index, :show]

  namespace :inquirer do
    resources :jobs do
      resources :bids, only: [:update] do
        member do
          patch :accept
        end
      end
    end
  end

  namespace :owner do
    resource :profile, only: [:show, :edit, :update]

    resources :drones
  end

  resources :jobs do
    collection do
      get 'latest', to: "jobs#latest"
    end
  end
end

app/views/shared/_cta.html.erb
<% unless cookies[:CallToAction] == "Accepted" %>
  <div class="container CTA hidden-xs hidden-sm" id="call-to-action">
    <div class="wrapper-cta">
      <div class="row">
        <div class="col-md-3 col-lg-2 flex-item">
          <%= image_tag "pilotCTA.png", style: "width:130px;" %>
        </div>
        <div class="col-md-3 col-lg-5 flex-item">
          <h2>Become a pilot</h2>
          <h5>and make beautiful pictures for your neighbours</h5>
        </div>
        <div class="col-md-3 col-lg-2 flex-item">
          <%= link_to "Become a pilot", jobs_path, onclick: "CallToAction()", class: "btn btn-lg btn-primary" %>
        </div>
        <div class="col-md-3 col-lg-1 flex-item">
          <%= link_to "", "", class: "fa fa-times fa-2x", onclick: "CallToAction()" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="wrapper">
<div class="container padded">
    <div class="row">
            <div class="col-xs-3">
                <ul class="list-unstyled">
                    <li class="footer-title">Menu<li>
                    <li><%= link_to t(".home", default: "Home"), root_path %></li>
                    <li><%= link_to t(".about", default: "About"), about_path %></li>
                    <li><%= link_to t(".discover", default: "Discover"), discover_path %></li>
                    <li><%= link_to t(".legislation", default: "Legislation"), legislation_path, class: "" %></li>
                </ul>
            </div>
            <vr></vr>
            <div class="col-xs-3">
                <ul class="list-unstyled">
                    <li class="footer-title">Users<li>
                    <li><%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path %></li>
                    <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path %></li>
                </ul>
            </div>
    </div>
    <hr>
    <div class="row">
            <div class="col-xs-8">
                <ul class="list-unstyled list-inline pull-left">
                    <li><%= link_to t(".terms", default: "Terms of Service"), terms_path %></li>
                </ul>
            </div>
            <div class="col-xs-4">
                <p class="text-muted pull-right">© 2016 Drone hubs. All rights reserved</p>
            </div>
        </div>
</div>
</div>

app/views/shared/_metatags.html.erb
<!-- Facebook Open Graph data -->
<meta property="og:title" content="DroneHubs" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://dronehubs.herokuapp.com/" />
<meta property="og:image" content="https://dronehubs.herokuapp.com/assets/logo-64acdc88cdc56b90e74b484e3aa6fdfd8fb81f47a210a83fb09807b4c2ef5d0f.png" />
<meta property="og:description" content="Connect through the air Hire your neighbour as a pilot or become the pilot yourself!." />
<meta property="og:site_name" content="DroneHubs" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@Tmstmrdng">
<meta name="twitter:title" content="DroneHubs">
<meta name="twitter:description" content="Connect through the air Hire your neighbour as a pilot or become the pilot yourself!.">
<meta name="twitter:creator" content="@Tmstmrdng">
<meta name="twitter:image:src" content="https://dronehubs.herokuapp.com/assets/logo-64acdc88cdc56b90e74b484e3aa6fdfd8fb81f47a210a83fb09807b4c2ef5d0f.png">

<!-- Google+ Schema.org markup -->
<meta itemprop="name" content="DroneHubs">
<meta itemprop="description" content="Connect through the air Hire your neighbour as a pilot or become the pilot yourself!.">
<meta itemprop="image" content="https://dronehubs.herokuapp.com/assets/logo-64acdc88cdc56b90e74b484e3aa6fdfd8fb81f47a210a83fb09807b4c2ef5d0f.png">

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? && current_user.owner %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
       <%= link_to t(".home", default: "Home"), root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".about", default: "About"), about_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".discover", default: "Discover"), discover_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".legislation", default: "Legislation"), legislation_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= link_to "", "", class: "fa fa-user navbar-wagon-link dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to owner_profile_path do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <% elsif user_signed_in? %>

        <!-- Profile picture and dropdown -->
        <%= link_to t(".home", default: "Home"), root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".about", default: "About"), about_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".discover", default: "Discover"), discover_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".legislation", default: "Legislation"), legislation_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= link_to "", "", class: "fa fa-user navbar-wagon-link dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to inquirer_jobs_path do %>
                <i class="fa fa-bookmark"></i>  <%= t ".myjobs", default: "My jobs" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".home", default: "Home"), root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".about", default: "About"), about_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".discover", default: "Discover"), discover_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".legislation", default: "Legislation"), legislation_path, class: "navbar-wagon-item navbar-wagon-link" %>
       <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "btn btn-primary login" %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t(".home", default: "Home"), root_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li> <%= link_to t(".discover", default: "Discover"), discover_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li> <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "btn btn-primary login" %></li>
      </ul>
    </div>
  </div>
</div>