config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get '/terms', to: "pages#terms"
  get '/legislation', to: "pages#legislation"
  get '/discover', to: "pages#discover"
  get '/about', to: "pages#about"


  devise_for :users

  resources :jobs, only: [:index, :show] do
    resources :bids, only: [:new, :create]
  end

  resources :pilots, only: [:index, :show]

  namespace :inquirer do
    resources :jobs do
      resources :bids, only: [:update] do
        member do
          patch :accept
        end
      end
    end
  end

  namespace :owner do
    resource :profile, only: [:show, :edit, :update]

    resources :drones
  end

  resources :jobs do
    collection do
      get 'latest', to: "jobs#latest"
    end
  end
end

app/controllers/owner/drones_controller.rb
class Owner::DronesController < ApplicationController
  respond_to :js, only: [:edit]
  def index
    @drones = current_user.drones
  end

  def show
    @drone = Drone.find(params[:id])
  end

  def new
    @drone = Drone.new
    @owner = current_user
  end

  def create
    @drone = Drone.new(drone_params)
    @drone.user = current_user
    @drone.save!
    redirect_to owner_profile_path
  end

  def edit
    @drone = Drone.find(params[:id])
  end

  def update
    @drone = Drone.find(params[:id])
    @drone.update!(drone_params)
    redirect_to owner_profile_path
  end

  def destroy
    @drone = Drone.find(params[:id])
    @drone.destroy!
    redirect_to owner_profile_path
  end

  private

  def drone_params
    params.require(:drone).permit(:brand, :model, :camera, :user_id, :photo, :photo_cache)
  end

end

app/controllers/owner/profiles_controller.rb
class Owner::ProfilesController < ApplicationController
  def show
    @owner = current_user
    @bids_amount = 0
    @jobs_amount = 0
    @jobs = []
    @bids = []

    @owner.drones.each do |drone|
      @bids_amount += drone.bids.size
      drone.bids.each do |bid|
        @bids << bid
      end
    end

    @owner.drones.each do |drone|
      drone.bids.each do |bid|
        if bid.status == "accepted"
          @jobs << { job: bid.job, drone: bid.drone }
          @jobs_amount += 1
        end
      end
    end

  end

  def edit
    @owner = current_user
  end

  def update
    @owner = current_user
    @owner.update(profile_params)
    if @owner.owner == true
      redirect_to owner_profile_path
    else
      redirect_to inquirer_jobs_path
    end
  end

  private

  def profile_params
    params.require(:user).permit(:first_name, :last_name, :description, :location, :profile_pic, :profile_pic_cache, :banner_pic, :banner_pic_cache)

  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    users = User.all
    @owners = []
    users.each do |user|
      if user.owner == true
      @owners << user
      end
    end
  end

  def show
    @owner = user.owner.find(params[:id])
  end
end

app/views/owner/profiles/_modal_edit.html.erb
<div class="modal fade" id="modal-profile" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= simple_form_for @owner, url: owner_profile_path do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit your Profile</h4>
      </div>
      <div class="modal-body">
        <%= f.error_notification %>

        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :profile_pic %>
        <%= f.input :profile_pic_cache, as: :hidden %>
        <%= f.input :banner_pic %>
        <%= f.input :banner_pic_cache, as: :hidden %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/owner/profiles/edit.html.erb
<h2>Edit your profile</h2>

<%= simple_form_for @owner, url: owner_profile_path do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :description %>
  <%= f.input :profile_pic %>
  <%= f.input :profile_pic_cache, as: :hidden %>
  <%= f.input :banner_pic %>
  <%= f.input :banner_pic_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/owner/profiles/show.html.erb
<div class="banner dashboard" style="background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.6)), url(<%= @owner.banner_pic %>);">
  <div class="banner-content">
    <% if @owner.profile_pic.nil? %>
      <%= image_tag "http://placehold.it/300x300", alt: "profile picture" %>
    <% else %>
      <%= cl_image_tag @owner.profile_pic.url, height: 300, width: 300, crop: :fill %>
    <% end %>
    <h1><%= @owner.first_name %> <%= @owner.last_name %></h1>
    <div class="banner-content-description"><%= @owner.description %></div>
    <div class="banner-content-buttons">
      <%= link_to "Edit your Profile", '#', { class: "btn btn-primary edit-profile", data: { toggle: "modal", target: "#modal-profile"}} %>
      <%= link_to "See your Profile", pilot_path(@owner), class: "btn btn-primary see-profile" %>
    </div>
  </div>
</div>



<div class="tab-box tab-profile">
  <h2 class="subtitle">
    <a href="#"><span class="tab active" data-target="#profile_drones">My Drones</span></a>

    <% if @jobs == [] || @jobs.nil? %>
      <a href="#"data-target="#profile_jobs"> <span class="tab hidden" data-target="#profile_jobs" >My Jobs(<%= @jobs_amount %>)</span></a>
    <% else %>
      <a href="#"data-target="#profile_jobs"> <span class="tab" data-target="#profile_jobs" >My Jobs(<%= @jobs_amount %>)</span></a>
    <% end %>

    <% if @bids == [] %>
      <a href="#"data-target="#profile_bids"><span class="tab hidden" data-target="#profile_bids">My Bids(<%= @bids_amount %>)</span></a>
    <% else %>
      <a href="#"data-target="#profile_bids"><span class="tab" data-target="#profile_bids">My Bids(<%= @bids_amount %>)</span></a>
    <% end %>

 </h2>

</div>
<div class="wrapper profile-wrapper">
  <div class="container">

    <div class="tab-content" id="profile_drones">
      <div class="container padded">
        <div class="row">
          <% if @owner.drones.nil? || @owner.drones == [] %>
            <h2>you don't have any drones add the moment. Add a few!</h2>
          <% else %>
          <% @owner.drones.each do |drone| %>
          <div class="col-xs-12 col-md-4">
            <div class="card">
              <% if drone[:photo] == nil %>
                <%= image_tag "http://placehold.it/300x300", size: "300x300", alt: "drone picture", class: "card-image drone" %>
              <% else %>
                <%= cl_image_tag drone.photo.url, height: 300, width: 300, crop: :fill, class: "card-image drone" %>
              <% end %>
              <div class="card-description drone">
                <h3><%= drone.brand %> <%= drone.model %></h3>
                <div class="drone-icons"><p>
                  <%= link_to owner_drone_path(drone) do %>
                  <i class="fa fa-search fa-2x" data-toggle="tooltip" data-placement="bottom" title="Details of this drone"></i>
                  <% end %>
                  <%= link_to edit_owner_drone_path(drone), remote: true do %>
                    <i class="fa fa-pencil fa-2x" data-toggle="tooltip" data-placement="bottom" title="Edit this drone"></i>
                  <% end %>
                  <%= link_to owner_drone_path(drone), method: :delete, data: { confirm: "Are you sure you want to delete the #{drone.brand} #{drone.model}?" } do %>
                  <i class="fa fa-trash fa-2x" data-toggle="tooltip" data-placement="bottom" title="Delete this drone"></i>
                  <% end %>
                </p></div>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
      <div class="padding-bottom text-center">

      <p><%= link_to "Add a Drone", new_owner_drone_path, { class: "btn btn-lg btn-success" } %></p>
      </div>
    </div>

    <div class="tab-content hidden" id="profile_jobs">
      <div class="container padded">
        <table class="table">
          <tr>
            <th>Job title</th>
            <th>Inquirer</th>
            <th>Drone</th>
          </tr>
          <% @jobs.each do |job| %>
          <tr>
            <td><%= link_to job[:job].title, job_path(job[:job]) %></td>
            <td><%= job[:job].user.first_name %></td>
            <td><div class="job-drone"><%= cl_image_tag job[:drone].photo.url , height: 100, witdh: 100, crop: :fill %> <span><%= job[:drone].brand %> <%= job[:drone].model %></span></div></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>

    <div class="tab-content hidden" id="profile_bids">
      <div class="container padded">
        <table class="table">
          <tr>
            <th>Amount</th>
            <th>Job title</th>
            <th>Inquirer</th>
            <th>Status</th>
          </tr>
          <% @owner.drones.each do |drone| %>
          <% drone.bids.each do |bid| %>
          <tr>
            <td>€<%= bid.amount %></td>
            <td><%= link_to bid.job.title, job_path(bid.job) %></td>
            <td><%= bid.job.user.first_name %></td>
            <td><%= bid.status %></td>
          </tr>
          <% end %>
          <% end %>
        </table>
      </div>
    </div>


  </div>
</div>
</div>

<%= render 'owner/profiles/modal_edit' %>
<%= render 'owner/drones/modal_edit_drone' %>